### ISSUE TITLE
tests that fail under current 4.3.0

### ISSUE THREAD

**Issue by idella** [enthought/chaco#112]
* python2_7: running distutils-r1_run_phase python_test

```python
.F..........................FF.......................................F.........................F............................................................
=================================================================================
FAIL: test_estimate_default_scale (chaco.scales.scales_test_case.BasicFormatterTestCase)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/chaco-4.3.0-r1/work/chaco-4.3.0-python2_7/lib/chaco/scales/scales_test_case.py", line 170, in test_estimate_default_scale
    self.assert_( err < 0.4 )
AssertionError: False is not true

======================================================================
FAIL: test_time_scale.test_tfrac_hours_04

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/chaco-4.3.0-r1/work/chaco-4.3.0-python2_7/lib/chaco/scales/tests/test_time_scale.py", line 51, in test_tfrac_hours_04
    assert base == 3600 * 3.0
AssertionError

======================================================================
FAIL: test_time_scale.test_tfrac_hours_05

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/chaco-4.3.0-r1/work/chaco-4.3.0-python2_7/lib/chaco/scales/tests/test_time_scale.py", line 57, in test_tfrac_hours_05
    assert base == 3600 * 12.0
AssertionError

======================================================================
FAIL: test_microsecond (chaco.scales.time_scale_test_case.TimeScaleTestCase)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/chaco-4.3.0-r1/work/chaco-4.3.0-python2_7/lib/chaco/scales/time_scale_test_case.py", line 156, in test_microsecond
    self.check_ticks(ticks, desired)
  File "/var/tmp/portage/dev-python/chaco-4.3.0-r1/work/chaco-4.3.0-python2_7/lib/chaco/scales/scales_test_case.py", line 16, in check_ticks
    self.assertEqual(len(ticks1),len(ticks2))
AssertionError: 10 != 7
-------------------- >> begin captured stdout << ---------------------
ticks:    [164083510.00000298, 164083510.000004, 164083510.00000498, 164083510.000006, 164083510.00000697, 164083510.000008, 164083510.00000897, 164083510.00000998, 164083510.00001097, 164083510.00001198]
desired:  [164083510.000003, 164083510.000004, 164083510.000005, 164083510.000006, 164083510.000007, 164083510.000008, 164083510.000009]

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: Borders should have the correct height and width.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/chaco-4.3.0-r1/work/chaco-4.3.0-python2_7/lib/chaco/tests/border_test_case.py", line 38, in test_draw_border_simple
    self.assertRavelEqual(actual, desired)
  File "/var/tmp/portage/dev-python/chaco-4.3.0-r1/work/chaco-4.3.0-python2_7/lib/chaco/tests/border_test_case.py", line 19, in assertRavelEqual
    self.assert_(alltrue(ravel(x) == ravel(y)), "\n%s\n !=\n%s" % (x, y))
AssertionError: 
[[255 255 255 255 255 255]
 [255   0   0   0   0 255]
 [255   0 255 255   0 255]
 [255   0 255 255   0 255]
 [255   0   0   0   0 255]
 [255 255 255 255 255 255]]
 !=
[[255 255 255 255 255 255]
 [255 255 255 255 255 255]
 [255   0   0   0 255 255]
 [255   0 255   0 255 255]
 [255   0   0   0 255 255]
 [255 255 255 255 255 255]]

----------------------------------------------------------------------
Ran 190 tests in 3.092s

FAILED (failures=5)
```

dev-python/chaco $ python -V
Python 2.7.3
enable version == 4.2.0
numpy version == 1.6.2

Please fix.

**Comment by corranwebster** [comment]
Timescale tests are hopefully fixed by #298, other tests should be fixed by #143.  Closing.
