### ISSUE TITLE
TimeScale tests failing on Mac OS X

### ISSUE THREAD

**Issue by pberkes** [enthought/chaco#153]
Tests pass on Travis CI, but I get a set of errors on my machine, all related to `chaco.scales`:

```
==> nosetests chaco
..........................FFFF...............F...........F.........F...F........................................................................................................................
======================================================================
FAIL: test_time_scale.test_tfrac_hours_02
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pberkes/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/pberkes/test_venvs/meta-ets/meta-ETS/chaco/chaco/scales/tests/test_time_scale.py", line 39, in test_tfrac_hours_02
    assert base == 0
AssertionError

======================================================================
FAIL: test_time_scale.test_tfrac_hours_03
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pberkes/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/pberkes/test_venvs/meta-ets/meta-ETS/chaco/chaco/scales/tests/test_time_scale.py", line 45, in test_tfrac_hours_03
    assert base == 3600 * 4
AssertionError

======================================================================
FAIL: test_time_scale.test_tfrac_hours_04
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pberkes/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/pberkes/test_venvs/meta-ets/meta-ETS/chaco/chaco/scales/tests/test_time_scale.py", line 51, in test_tfrac_hours_04
    assert base == 3600 * 3.0
AssertionError

======================================================================
FAIL: test_time_scale.test_tfrac_hours_05
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pberkes/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/pberkes/test_venvs/meta-ets/meta-ETS/chaco/chaco/scales/tests/test_time_scale.py", line 57, in test_tfrac_hours_05
    assert base == 3600 * 12.0
AssertionError

======================================================================
FAIL: test_time_scale.test_trange_hours_07
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pberkes/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/pberkes/test_venvs/meta-ets/meta-ETS/chaco/chaco/scales/tests/test_time_scale.py", line 149, in test_trange_hours_07
    assert r == [0.0, 7200.0]
AssertionError

======================================================================
FAIL: test_yearly_scales (chaco.scales.time_scale_test_case.CalendarScaleSystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pberkes/test_venvs/meta-ets/meta-ETS/chaco/chaco/scales/time_scale_test_case.py", line 174, in test_yearly_scales
    self.check_ticks(ticks, desired)
  File "/Users/pberkes/test_venvs/meta-ets/meta-ETS/chaco/chaco/scales/scales_test_case.py", line 16, in check_ticks
    self.assertEqual(len(ticks1),len(ticks2))
AssertionError: 7 != 8

======================================================================
FAIL: test_day_of_month (chaco.scales.time_scale_test_case.TimeScaleTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pberkes/test_venvs/meta-ets/meta-ETS/chaco/chaco/scales/time_scale_test_case.py", line 129, in test_day_of_month
    self.check_ticks(ts.ticks(start,end), desired)
  File "/Users/pberkes/test_venvs/meta-ets/meta-ETS/chaco/chaco/scales/scales_test_case.py", line 18, in check_ticks
    self.assertAlmostEqual(t1, t2, 6)
AssertionError: 1110924000.0 != 1110841200.0 within 6 places

======================================================================
FAIL: test_month_of_year (chaco.scales.time_scale_test_case.TimeScaleTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pberkes/test_venvs/meta-ets/meta-ETS/chaco/chaco/scales/time_scale_test_case.py", line 143, in test_month_of_year
    self.check_ticks(ts.ticks(start,end), desired)
  File "/Users/pberkes/test_venvs/meta-ets/meta-ETS/chaco/chaco/scales/scales_test_case.py", line 18, in check_ticks
    self.assertAlmostEqual(t1, t2, 6)
AssertionError: 1104616800.0 != 1104534000.0 within 6 places

----------------------------------------------------------------------
Ran 192 tests in 0.347s

FAILED (failures=8)
```

**Comment by corranwebster** [comment]
Fixed by #298
