### ISSUE TITLE
Remove chaco.plot_canvas and related code

### ISSUE THREAD

**Issue by corranwebster** [enthought/chaco#254]
This code is not currently used and dates from Chaco 1, I think.  There is an example of its use in the demo code, but it appears old and broken (at least on OS X).

This should probably be removed, although such a change is technically not backwards compatible.

**Comment by rahulporuri** [comment]
just to confirm, the modules being removed in #576  are

- `chaco.plot_canvas`
- `chaco.plot_canvas_toolbar`
- example code which makes use of the above two modules

**Comment by rahulporuri** [comment]
I see the following exception when i try to run some of the examples

```
(chaco-test-3.6-pyqt5)C:\Users\rporuri\work\github\ets\chaco\examples\demo\canvas>python cliptest.py
Traceback (most recent call last):
  File "cliptest.py", line 95, in <module>
    demo = demo_main(MainFrame, size=(800,800), title="ClipTest")
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\enable\example_support.py", line 57, in demo_main
    demo_class().configure_traits()
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traits\has_traits.py", line 2095, in configure_traits
    args,
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\toolkit.py", line 233, in view_application
    context, view, kind, handler, id, scrollable, args
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\view_application.py", line 84, in view_application
    context, view, kind, handler, id, scrollable, args
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\view_application.py", line 126, in __init__
    args=self.args,
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\view.py", line 462, in ui
    ui.ui(parent, kind)
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\ui.py", line 244, in ui
    self.rebuild(self, parent)
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\toolkit.py", line 163, in ui_live
    ui_live.ui_live(ui, parent)
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_live.py", line 43, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_live.py", line 65, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_base.py", line 286, in display_ui
    ui.owner.init(ui, parent, style)
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_live.py", line 225, in init
    self.add_contents(panel(ui), bbox)
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 259, in panel
    panel = _GroupPanel(content[0], ui).control
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 617, in __init__
    layout = self._add_items(content, inner)
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\ui_panel.py", line 883, in _add_items
    ui, object, name, item.tooltip, None
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\editor_factory.py", line 132, in simple_editor
    description=description,
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\traitsui\editor.py", line 459, in __init__
    self.old_value = getattr(self.object, self.name)
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\enable\example_support.py", line 48, in _component_default
    return self._create_component()
  File "C:\Users\rporuri\.edm\envs\chaco-test-3.6-pyqt5\lib\site-packages\enable\example_support.py", line 53, in _create_component
    raise NotImplementedError
NotImplementedError
```

Note that there are only two outcomes with the examples - either they dont do anything at all or they raise this ^ exception.

**Comment by aaronayres35** [comment]
> I see the following exception when i try to run some of the examples
>
> Note that there are only two outcomes with the examples - either they dont do anything at all or they raise this ^ exception.

Ah i meant to comment on this earlier, but must have forgotten...
Examples need to define a `_create_component` method.  For example, the `canvas.py` example was working for me simply by renaming `_create_viewport` to `_create_component`

**Comment by corranwebster** [comment]
Having a little deeper look at the examples.  I think the `cliptest.py` example really belongs as an Enable demo - there is nothing it does that is particularly Chaco-related.  It needs `create_window` to `creat_component` and be modified to return `outer`.

**Comment by corranwebster** [comment]
OK.  The canvas demo is currently broken because it is designed to work with the custom multitouch interface that Enthought built as a side-project back in 2007-ish - the interface is predicated on being able to click on two buttons at the same time, but you can't do that with a mouse...

It can probably be fixed up by making the toolbar toggle things.

If it can be made to work, it may be worth re-assessing whether PlotCanvas should be removed.

**Comment by corranwebster** [comment]
OK, digging in, I have had somewhat of a change of heart.  `PlotCanvas` seems fine, but the demo that uses it is badly broken without multitouch support and has a number of other bugs besides.

The desired behaviour of the demo (as best as I can tell) is:
- click one button, get a line plot of values
- click two buttons, get a scatterplot of the two sets of values
- click a third, fourth, etc. button, get a scatter plot of the last 2 buttons selected
- drag a plot, get a copy of it (this code is pretty egregiously hacky)
- there is also a tool for synchronizing axes together, but I wasn't able to get to a point where I could test it.

There's also a _bunch_ of custom multi-touch support code in there.

**Comment by rahulporuri** [comment]
closing this issue as we have decided to not remove the `chaco.plot_canvas` code - and instead we'll work on fixing the canvas examples in chaco.
