### ISSUE TITLE
DataLabel bubble style uncaught exception

### ISSUE THREAD

**Issue by nslavich** [enthought/chaco#281]
I get an uncaught exception in chaco 4.5.0 when I create a DataLabel with label_style = 'bubble' and no arrow:

Traceback (most recent call last):
  File "/home/slavich/workspace/env/scopeview2/local/lib/python2.7/site-packages/enable-4.5.1-py2.7-linux-x86_64.egg/enable/qt4/base_window.py", line 198, in paintEvent
    self.handler.paintEvent(event)
  File "/home/slavich/workspace/env/scopeview2/local/lib/python2.7/site-packages/enable-4.5.1-py2.7-linux-x86_64.egg/enable/qt4/base_window.py", line 50, in paintEvent
    self._enable_window._paint(event)
  File "/home/slavich/workspace/env/scopeview2/local/lib/python2.7/site-packages/enable-4.5.1-py2.7-linux-x86_64.egg/enable/abstract_window.py", line 467, in _paint
    self.component.draw(gc, view_bounds=(0, 0, size[0], size[1]))
  File "/home/slavich/workspace/env/scopeview2/local/lib/python2.7/site-packages/enable-4.5.1-py2.7-linux-x86_64.egg/enable/component.py", line 424, in draw
    self._draw(gc, view_bounds, mode)
  File "/home/slavich/workspace/env/scopeview2/local/lib/python2.7/site-packages/enable-4.5.1-py2.7-linux-x86_64.egg/enable/component.py", line 773, in _draw
    self._dispatch_draw("overlay", gc, view_bounds, mode)
  File "/home/slavich/workspace/env/scopeview2/local/lib/python2.7/site-packages/enable-4.5.1-py2.7-linux-x86_64.egg/enable/container.py", line 272, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/home/slavich/workspace/env/scopeview2/local/lib/python2.7/site-packages/enable-4.5.1-py2.7-linux-x86_64.egg/enable/container.py", line 272, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/home/slavich/workspace/env/scopeview2/local/lib/python2.7/site-packages/enable-4.5.1-py2.7-linux-x86_64.egg/enable/component.py", line 796, in _dispatch_draw
    handler(gc, view_bounds, mode)
  File "/home/slavich/workspace/env/scopeview2/local/lib/python2.7/site-packages/enable-4.5.1-py2.7-linux-x86_64.egg/enable/component.py", line 874, in _draw_overlay
    overlay.overlay(self, gc, view_bounds, mode)
  File "/home/slavich/workspace/env/scopeview2/local/lib/python2.7/site-packages/chaco/data_label.py", line 314, in overlay
    mode=mode)
  File "/home/slavich/workspace/env/scopeview2/local/lib/python2.7/site-packages/chaco/data_label.py", line 409, in _render_bubble
    arrow_len = sqrt((px - bx) ** 2 + (py - by) ** 2)
UnboundLocalError: local variable 'bx' referenced before assignment

Looking at the source in data_label.py, it is apparent that neither bx nor by get initialized if self.arrow_visible is false.

**Comment by WarrenWeckesser** [comment]
Grrr... who wrote that code?  :stuck_out_tongue_winking_eye:

Fix in https://github.com/enthought/chaco/pull/282
