### ISSUE TITLE
Python 3 installation fails on macOS + Anaconda

### ISSUE THREAD

**Issue by magonser** [enthought/chaco#319]
Hello all, 

I want to use chaco in Python 3. I have tried to install it in an conda anvironment via pip, as well as building chaco and enable packages from source on my Mac with macOS Sierra. 

My experiences:
1) Trying to install chaco via 
$conda create -n test python=3.5 numpy 
$source activate test
$pip install chaco
Using cached chaco-4.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/j6/2d0_2nxx3cd88j6ml7wn859c0000gn/T/pip-build-6q116tt6/chaco/setup.py", line 9, in <module>
        execfile(join('chaco', '**init**.py'), info)
    NameError: name 'execfile' is not defined

2) Trying to build enable and chaco via their respective `python setup.py install` in an conda environment as above will give me lateron (when trying one of the chaco-demos) a Python Error such as: 

$ python simple_line.py 
/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/chaco-4.6.0.dev239-py3.5-macosx-10.6-x86_64.egg/chaco/array_data_source.py:123: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._data = newdata
Traceback (most recent call last):
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/plat_support.py", line 165, in __init__
    self.this.append(this)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/plat_support.py", line 157, in <lambda>
    **getattr** = lambda self, name: _swig_getattr(self, PixelMap, name)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/plat_support.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'PixelMap' object has no attribute 'this'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/enable/qt4/base_window.py", line 198, in paintEvent
    self.handler.paintEvent(event)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/enable/qt4/base_window.py", line 50, in paintEvent
    self._enable_window._paint(event)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/enable/abstract_window.py", line 459, in _paint
    self._gc = self._create_gc(size)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/enable/qt4/image.py", line 23, in _create_gc
    bottom_up = 0)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/__init__.py", line 36, in **init**
    bool(bottom_up)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/plat_support.py", line 166, in **init**
    except builtins.Exception:
NameError: name 'builtins' is not defined
Traceback (most recent call last):
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/plat_support.py", line 165, in **init**
    self.this.append(this)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/plat_support.py", line 157, in <lambda>
    **getattr** = lambda self, name: _swig_getattr(self, PixelMap, name)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/plat_support.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'PixelMap' object has no attribute 'this'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/enable/qt4/base_window.py", line 198, in paintEvent
    self.handler.paintEvent(event)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/enable/qt4/base_window.py", line 50, in paintEvent
    self._enable_window._paint(event)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/enable/abstract_window.py", line 459, in _paint
    self._gc = self._create_gc(size)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/enable/qt4/image.py", line 23, in _create_gc
    bottom_up = 0)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/__init__.py", line 36, in **init**
    bool(bottom_up)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/plat_support.py", line 166, in **init**
    except builtins.Exception:
NameError: name 'builtins' is not defined
Traceback (most recent call last):
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/plat_support.py", line 165, in **init**
    self.this.append(this)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/plat_support.py", line 157, in <lambda>
    **getattr** = lambda self, name: _swig_getattr(self, PixelMap, name)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/plat_support.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'PixelMap' object has no attribute 'this'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/enable/qt4/base_window.py", line 198, in paintEvent
    self.handler.paintEvent(event)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/enable/qt4/base_window.py", line 50, in paintEvent
    self._enable_window._paint(event)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/enable/abstract_window.py", line 459, in _paint
    self._gc = self._create_gc(size)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/enable/qt4/image.py", line 23, in _create_gc
    bottom_up = 0)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/__init__.py", line 36, in **init**
    bool(bottom_up)
  File "/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev250-py3.5-macosx-10.6-x86_64.egg/kiva/agg/plat_support.py", line 166, in **init**
    except builtins.Exception:
NameError: name 'builtins' is not defined

I have tried to pin down the problem, but since I am not an expert on setuptools, I am pretty much lost. So could anyone please assist me in trying to get chaco run on py35?

Thanks, Markus

Btw: what is the plan for other Enthough libraries, namely envisage, mayavi and maybe enaml?

**Comment by prabhuramachandran** [comment]
@magonser -- Mayavi already works with Python3 and there are some packages here: https://anaconda.org/menpo/mayavi

**Comment by corranwebster** [comment]
@magonser Thanks for trying things out - are you running from the current master branch from github for both Enable and Chaco?  The 4.5 releases don't have Python 3 support, but the current head of development should.

That said, there are some issues with Enable on Mac OS.  You will likely want to follow https://github.com/enthought/enable/pull/242

Envisage and Mayavi have Python 3 support.  SciMath is underway.  Codetools would need a re-write of its code analysis library to support Python 3. Enaml is no longer an Enthought project.

**Comment by magonser** [comment]
Hello @corranwebster @prabhuramachandran ,

thanks for your quick answers! I am sorry, that I have missed out on checking out the correct commits - it works fine now. I've used the current PR-branch of enthought/enable#242 and the HEAD of chaco to `python setup.py install` both in my conda environment. Initial tests on demos work fine. That means I can start developing on py35 + chaco now. 

It is great, that the GUI-Toolsuite (traits, mayavi, chaco, etc) gets ported to Python 3 as I haven't found a similar alternative for engineering GUIs. Thank you so much for that. 

Best Regards,

Markus

FYI there are the following warnings: 

/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/chaco-4.6.0.dev239-py3.5-macosx-10.6-x86_64.egg/chaco/array_data_source.py:123: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._data = newdata
/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/chaco-4.6.0.dev239-py3.5-macosx-10.6-x86_64.egg/chaco/axis.py:498: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  for tickpos in mapped_tick_positions]))
/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/chaco-4.6.0.dev239-py3.5-macosx-10.6-x86_64.egg/chaco/axis.py:499: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._tick_label_list = tick_list
/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/chaco-4.6.0.dev239-py3.5-macosx-10.6-x86_64.egg/chaco/axis.py:500: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._tick_label_positions = self._tick_positions
/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev258-py3.5-macosx-10.6-x86_64.egg/kiva/fonttools/font_manager.py:1306: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev258-py3.5-macosx-10.6-x86_64.egg/kiva/fonttools/font_manager.py:1316: UserWarning: findfont: Could not match (['Bitstream Vera Sans'], 'normal', None, 'normal', 500, 10.0). Returning /usr/X11/lib/X11/fonts/TTF/Vera.ttf
  UserWarning)
/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev258-py3.5-macosx-10.6-x86_64.egg/kiva/fonttools/font_manager.py:1316: UserWarning: findfont: Could not match (['Bitstream Vera Sans'], 'normal', None, 'normal', 500, 12.0). Returning /usr/X11/lib/X11/fonts/TTF/Vera.ttf
  UserWarning)
/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev258-py3.5-macosx-10.6-x86_64.egg/kiva/fonttools/font_manager.py:1306: UserWarning: findfont: Font family ['Arial'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
/Users/Markus/anaconda/envs/chaco3/lib/python3.5/site-packages/enable-4.6.0.dev258-py3.5-macosx-10.6-x86_64.egg/kiva/fonttools/font_manager.py:1316: UserWarning: findfont: Could not match (['Bitstream Vera Sans'], 'normal', None, 'normal', 500, 24.0). Returning /usr/X11/lib/X11/fonts/TTF/Vera.ttf
  UserWarning)

**Comment by corranwebster** [comment]
Thanks for the reports of the warnings.  The numpy ones are a known issue with the `Array` trait which I think has been fixed in the current master of Traits, but is (currently) harmless.

The other warnings look like they are reporting that a particular font isn't available and that it's returning an alternative.  Presuming that the text looks fine, it's probably also harmless.

**Comment by corranwebster** [comment]
SInce there's been no further issues, I'll close this for now.

**Comment by magonser** [comment]
Thanks @corranwebster it worked out!
