### ISSUE TITLE
Test failures with Numpy 1.12

### ISSUE THREAD

**Issue by jvkersch** [enthought/chaco#346]
```
13:11 $ python -m unittest discover chaco
.........../Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/chaco/array_data_source.py:123: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._data = newdata
/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/traits/trait_handlers.py:1603: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if value in self.values:
/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/chaco/image_data.py:194: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._data = newdata
.EEsE..E.....
======================================================================
ERROR: test_colormap_updated (chaco.tests.test_colormapped_scatterplot.TestColormappedScatterplot)
If colormapper updated then we need to redraw
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/chaco/tests/test_colormapped_scatterplot.py", line 41, in setUp
    self.gc = PlotGraphicsContext((50, 50))
  File "/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/chaco/plot_graphics_context.py", line 27, in __init__
    super(PlotGraphicsContextMixin, self).__init__(size_or_ary, *args, **kw)
  File "/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/kiva/agg/agg.py", line 1505, in init
    ary = zeros((height,width,img_depth),uint8)
TypeError: 'float' object cannot be interpreted as an index

======================================================================
ERROR: test_scatter_circle (chaco.tests.test_colormapped_scatterplot.TestColormappedScatterplot)
Coverage test to check circles work
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/chaco/tests/test_colormapped_scatterplot.py", line 41, in setUp
    self.gc = PlotGraphicsContext((50, 50))
  File "/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/chaco/plot_graphics_context.py", line 27, in __init__
    super(PlotGraphicsContextMixin, self).__init__(size_or_ary, *args, **kw)
  File "/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/kiva/agg/agg.py", line 1505, in init
    ary = zeros((height,width,img_depth),uint8)
TypeError: 'float' object cannot be interpreted as an index

======================================================================
ERROR: test_scatter_render (chaco.tests.test_colormapped_scatterplot.TestColormappedScatterplot)
Coverage test to check basic case works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/chaco/tests/test_colormapped_scatterplot.py", line 41, in setUp
    self.gc = PlotGraphicsContext((50, 50))
  File "/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/chaco/plot_graphics_context.py", line 27, in __init__
    super(PlotGraphicsContextMixin, self).__init__(size_or_ary, *args, **kw)
  File "/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/kiva/agg/agg.py", line 1505, in init
    ary = zeros((height,width,img_depth),uint8)
TypeError: 'float' object cannot be interpreted as an index

======================================================================
ERROR: test_data_label_arrow_not_visible (chaco.tests.test_data_label.DataLabelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/chaco/tests/test_data_label.py", line 25, in test_data_label_arrow_not_visible
    gc = PlotGraphicsContext(size)
  File "/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/chaco/plot_graphics_context.py", line 27, in __init__
    super(PlotGraphicsContextMixin, self).__init__(size_or_ary, *args, **kw)
  File "/Users/jvkersch/tmp/chaco-pg/chacha/lib/python2.7/site-packages/kiva/agg/agg.py", line 1505, in init
    ary = zeros((height,width,img_depth),uint8)
TypeError: 'float' object cannot be interpreted as an index

----------------------------------------------------------------------
Ran 24 tests in 2.842s

FAILED (errors=4, skipped=1)
```

**Comment by stevenjkern** [comment]
Are these failures seen locally, and if so is `enable` on `master`? @rkern's changes in enthought/enable#269 should have fixed these.

**Comment by jvkersch** [comment]
@stevenjkern You're right, these come from Enable (I was using a released version, which doesn't have Robert's changes).
