### ISSUE TITLE
wxpython + python 3

### ISSUE THREAD

**Issue by lfriedri** [enthought/chaco#352]
Is chaco supported for python 3 + wxpython?
If not, is the support planned for the future?

**Comment by lfriedri** [comment]
With the combination of
python3.6 64bit
wxpython 4.0.0a3
enable 4.6.2
chaco 4.61
I get the following traceback when I run chaco/examples/demo/simple_line.py:

``C:\Users\my_name\Documents\my_project>"WinPython-64bit-3.6.1.0Zero__wx_test3\scripts\python.bat" "simple_line.py"
Traceback (most recent call last):
  File "simple_line.py", line 27, in <module>
    from enable.api import Component, ComponentEditor
  File "C:\Users\my_name\Documents\my_project\WinPython-64bit-3.6.1.0Zero__wx_test3\python-3.6.1.amd64\lib\site-packages\enable\api.py", line 8, in <module>
    from .base import IDroppedOnHandler, TOP, VCENTER, BOTTOM, LEFT, HCENTER, RIGHT, \
  File "C:\Users\my_name\Documents\my_project\WinPython-64bit-3.6.1.0Zero__wx_test3\python-3.6.1.amd64\lib\site-packages\enable\base.py", line 35, in <module>
    from .colors import color_table, transparent_color
  File "C:\Users\my_name\Documents\my_project\WinPython-64bit-3.6.1.0Zero__wx_test3\python-3.6.1.amd64\lib\site-packages\enable\colors.py", line 179, in <module>
    from traitsui.wx.color_editor \
  File "C:\Users\my_name\Documents\my_project\WinPython-64bit-3.6.1.0Zero__wx_test3\python-3.6.1.amd64\lib\site-packages\traitsui\wx\__init__.py", line 26, in <module>
    from . import toolkit
  File "C:\Users\my_name\Documents\my_project\WinPython-64bit-3.6.1.0Zero__wx_test3\python-3.6.1.amd64\lib\site-packages\traitsui\wx\toolkit.py", line 55, in <module>
    from pyface.wx.drag_and_drop \
  File "C:\Users\my_name\Documents\my_project\WinPython-64bit-3.6.1.0Zero__wx_test3\python-3.6.1.amd64\lib\site-packages\pyface\wx\drag_and_drop.py", line 60, in <module>
    PythonObject = wx.CustomDataFormat('PythonObject')
AttributeError: module 'wx' has no attribute 'CustomDataFormat'

C:\Users\my_name\Documents\my_project>

**Comment by corranwebster** [comment]
No, WxPython + Python 3 is not currently supported.  For Chaco itself, it should be straightforward, but work needs to be done downstream in Pyface, TraitsUI and Enable to support WxPython 4 (which is the error that you are seeing there).

Support will eventually come, but it's not a high priority for us at Enthought right now because we are either using Qt or Python 2.7 on all our projects.

If you are willing to work on the bleeding edge, see https://github.com/enthought/traitsui/issues/356 for discussions, and I think pointers to forks with WxPython 4 compatible code.

**Comment by lfriedri** [comment]
Thank you for the answer and the pointer to the related discussion.
No, I won't have energy for working on the code itself. My current goal is to plug together a portable python version that supports all my needs for specific packages and is at the same time as recent as possible. I think it will be python 2.7 then,... too bad ;-)

**Comment by corranwebster** [comment]
This doesn't solve your WxPython + Python 3 use-case, but have you looked at the EDM tool we provide http://docs.enthought.com/edm/ ?  It's free to use, designed to support putting together portable Python versions, we use it extensively to support our business use-cases.  If you have, I apologise for the ad 😄 

I will leave this issue open as a reminder that WxPython + Python 3 is something that we eventually want to support.

**Comment by lfriedri** [comment]
Thanks for the pointer. No I did not know edm. From the website I would not have guessed that you can generate PORTABLE python versions. Currently, I am looking at WinPython for that.
