### ISSUE TITLE
Docs don't build

### ISSUE THREAD

**Issue by jvkersch** [enthought/chaco#380]
**Problem Description**

Not sure about the underlying issue (or why this has cropped up now) but doing a simple `make html` in the docs folder results in a traceback in one of the Sphinx extensions.

```
05:10 $ cat /var/folders/yx/p6tl77d502qc2v1srt84n91r0000gq/T/sphinx-err-a9YfOQ.log
# Sphinx version: 1.5.5
# Python version: 2.7.13 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Users/jvankerschaver/.edm/envs/docs-generating-env/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/Users/jvankerschaver/.edm/envs/docs-generating-env/lib/python2.7/site-packages/sphinx/application.py", line 199, in __init__
    self.setup_extension(extension)
  File "/Users/jvankerschaver/.edm/envs/docs-generating-env/lib/python2.7/site-packages/sphinx/application.py", line 512, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/Users/jvankerschaver/src/enthought/chaco/docs/source/sphinxext/traitsdoc.py", line 7, in <module>
    from . import docscrape
ValueError: Attempted relative import in non-package
```

**Reproduction Steps:**

- Install the package
- `cd docs; make html`

**Comment by jdeschenes** [comment]
Looks like it's related to the python 3 update. an __init__ file would probably fix this.
