### ISSUE TITLE
Lasso selection breaks with numpy 1.13

### ISSUE THREAD

**Issue by jwiggins** [enthought/chaco#408]
**Problem Description**
When running the scatter select example (chaco/examples/demo/basic/scatter_select.py) with numpy 1.13.3, an exception is raised by enable's `points_in_polygon` function, which expects arrays passed to it to be C-contiguous.

```
Traceback (most recent call last):
  File "/Users/jwiggins/.edm/envs/test_env/lib/python2.7/site-packages/enable/qt4/base_window.py", line 229, in mouseReleaseEvent
    self.handler.mouseReleaseEvent(event)
  File "/Users/jwiggins/.edm/envs/test_env/lib/python2.7/site-packages/enable/qt4/base_window.py", line 118, in mouseReleaseEvent
    self._enable_window._handle_mouse_event(name + "_up", event)
  File "/Users/jwiggins/.edm/envs/test_env/lib/python2.7/site-packages/enable/abstract_window.py", line 349, in _handle_mouse_event
    self.component.dispatch(mouse_event, event_name)
  File "/Users/jwiggins/.edm/envs/test_env/lib/python2.7/site-packages/enable/component.py", line 921, in dispatch
    self._new_dispatch(event, suffix)
  File "/Users/jwiggins/.edm/envs/test_env/lib/python2.7/site-packages/enable/component.py", line 961, in _new_dispatch
    self._dispatch_stateful_event(event, suffix)
  File "/Users/jwiggins/.edm/envs/test_env/lib/python2.7/site-packages/enable/container.py", line 514, in _dispatch_stateful_event
    component.dispatch(event, suffix)
  File "/Users/jwiggins/.edm/envs/test_env/lib/python2.7/site-packages/enable/component.py", line 921, in dispatch
    self._new_dispatch(event, suffix)
  File "/Users/jwiggins/.edm/envs/test_env/lib/python2.7/site-packages/enable/component.py", line 949, in _new_dispatch
    self._active_tool.dispatch(event, suffix)
  File "/Users/jwiggins/.edm/envs/test_env/lib/python2.7/site-packages/enable/interactor.py", line 94, in dispatch
    self._dispatch_stateful_event(event, suffix)
  File "/Users/jwiggins/.edm/envs/test_env/lib/python2.7/site-packages/enable/interactor.py", line 110, in _dispatch_stateful_event
    handler(event)
  File "/Users/jwiggins/.edm/envs/test_env/lib/python2.7/site-packages/chaco/tools/lasso_selection.py", line 159, in selecting_left_up
    return self.selecting_mouse_up(event)
  File "/Users/jwiggins/.edm/envs/test_env/lib/python2.7/site-packages/chaco/tools/lasso_selection.py", line 172, in selecting_mouse_up
    self._update_selection()
  File "/Users/jwiggins/.edm/envs/test_env/lib/python2.7/site-packages/chaco/tools/lasso_selection.py", line 270, in _update_selection
    data, self._active_selection, False).astype(bool, copy=False)
  File "kiva/_cython_speedups.pyx", line 68, in kiva._cython_speedups.points_in_polygon (kiva/_cython_speedups.cpp:3068)
  File "kiva/stringsource", line 644, in View.MemoryView.memoryview_cwrapper (kiva/_cython_speedups.cpp:11770)
  File "kiva/stringsource", line 345, in View.MemoryView.memoryview.__cinit__ (kiva/_cython_speedups.cpp:8005)
ValueError: ndarray is not C-contiguous
```

**Reproduction Steps:**

Run the scatter select example and make a selection:
```
$ edm install -e chaco_bug -y numpy pyqt chaco
$ edm run -e chaco_bug -- python ~/source/chaco/examples/demo/basic/scatter_select.py
```

**Expected behavior:**

An exception should not be raised when a selection is made.

**OS, Python version:**
OS X 10.13.5
Python 2.7.13

**Package versions**
appdirs            1.4.3-1
chaco              4.7.1-2
distribute_remove  1.0.0-4
enable             4.7.1-3
fonttools          3.18.0-1
freetype           2.5.3-7
kiwisolver         0.1.3-3
libjpeg            7.0-5
libopenjpeg        2.1.0-4
libpng             1.6.12-6
mkl                2017.0.3-1
numpy              1.13.3-3
packaging          16.8-2
pil_remove         1.0.0-3
pillow             4.0.0-1
pip                10.0.1-1
pyface             6.0.0-1
pygments           2.2.0-1
pyparsing          2.2.0-1
pyqt               4.12-1
qt                 4.8.7-7
setuptools         38.2.5-1
sip                4.19.2-2
six                1.10.0-1
traits             4.6.0-1
traitsui           6.0.0-1

**Comment by jwiggins** [comment]
This might be caused by a change in Cython? I see the exact same behavior between both numpy 1.11.3 and 1.13.3. Namely, both produce a non-contiguous array when transposing, and `asarray` does not create a contiguous array (`'strides': None`).

**numpy 1.11.3**:
```
Python 2.7.13 |Enthought, Inc. (x86_64)| (default, Mar  2 2017, 08:20:50) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> index = np.arange(0, 100)
>>> value = np.arange(100, 200)
>>> arr = np.array((index, value))
>>> arr.__array_interface__
{'descr': [('', '<i8')], 'strides': None, 'shape': (2, 100), 'version': 3, 'typestr': '<i8', 'data': (4312921088, False)}
>>> tr = arr.T
>>> tr.__array_interface__
{'descr': [('', '<i8')], 'strides': (8, 800), 'shape': (100, 2), 'version': 3, 'typestr': '<i8', 'data': (4312921088, False)}
>>> pts = np.asarray(tr, dtype=np.float64)
>>> pts.__array_interface__
{'descr': [('', '<f8')], 'strides': (8, 800), 'shape': (100, 2), 'version': 3, 'typestr': '<f8', 'data': (4320136192, False)}
```

**numpy 1.13.3**:
```
Enthought Deployment Manager -- https://www.enthought.com
Python 2.7.13 |Enthought, Inc. (x86_64)| (default, Mar  2 2017, 08:20:50) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> index = np.arange(0, 100)
>>> value = np.arange(100, 200)
>>> arr = np.array((index, value))
>>> arr.__array_interface__
{'descr': [('', '<i8')], 'strides': None, 'shape': (2, 100), 'version': 3, 'typestr': '<i8', 'data': (4328643072, False)}
>>> tr = arr.T
>>> tr.__array_interface__
{'descr': [('', '<i8')], 'strides': (8, 800), 'shape': (100, 2), 'version': 3, 'typestr': '<i8', 'data': (4328643072, False)}
>>> pts = np.asarray(tr, dtype=np.float64)
>>> pts.__array_interface__
{'descr': [('', '<f8')], 'strides': (8, 800), 'shape': (100, 2), 'version': 3, 'typestr': '<f8', 'data': (4304680448, False)}
```

**Comment by corranwebster** [comment]
My suspicion is that:

- the new `points_in_polygon` hadn't been extensively tested against all of chaco, so we hadn't noticed the requirement for C-contiguous code
- the old `points_in_polygon` was SWIG-based and part of the Agg backend, so it either dealt with non-C-contiguous arrays just fine or, alternatively, there has been a long-standing bug in the code (probably he first)

**Comment by jwiggins** [comment]
I was a bit thrown off, because the original bug report (from a customer) saw the bug show up when they upgraded numpy from 1.11.3 -> 1.13.3. However, I tried my reproduction steps with `$ edm install -e chaco_bug -y numpy^=1.11.3 pyqt chaco` and the bug didn't go away.

It's fixed now, at least...
