### ISSUE TITLE
Demo financial_plot_dates.py break when zooming out

### ISSUE THREAD

**Issue by ku-ya** [enthought/chaco#415]
**Problem Description**
financial_plot_dates.py break when zooming out
**Reproduction Steps:**
Run the file and keep zooming out.
**Expected behavior:**
Plot disappear and raise the error
```
/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/chaco/scales/safetime.py:37: UserWarning: Timestamp out of range.  Returning safe default value.
  warnings.warn("Timestamp out of range.  Returning safe default value.")
Traceback (most recent call last):
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/enable/qt4/base_window.py", line 202, in paintEvent
    self.handler.paintEvent(event)
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/enable/qt4/base_window.py", line 54, in paintEvent
    self._enable_window._paint(event)
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/enable/abstract_window.py", line 468, in _paint
    self.component.draw(gc, view_bounds=(0, 0, size[0], size[1]))
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/enable/component.py", line 427, in draw
    self._draw(gc, view_bounds, mode)
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/enable/component.py", line 779, in _draw
    self._dispatch_draw(layer, gc, view_bounds, mode)
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/enable/container.py", line 272, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/enable/component.py", line 799, in _dispatch_draw
    handler(gc, view_bounds, mode)
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/enable/component.py", line 887, in _draw_underlay
    underlay.overlay(self, gc, view_bounds, mode)
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/chaco/grid.py", line 307, in overlay
    self._compute_ticks(other_component)
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/chaco/grid.py", line 255, in _compute_ticks
    scale=scale)
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/chaco/scales_tick_generator.py", line 31, in get_ticks
    ticks = self.scale.ticks(data_low, data_high)
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/chaco/scales/scales.py", line 446, in ticks
    ticks = scale.ticks(start, end, numticks)
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/chaco/scales/time_scale.py", line 291, in ticks
    return trange(start, end, **{self.unit: self.val})
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/chaco/scales/time_scale.py", line 179, in trange
    return trange_years(start, end, value)
  File "/Users/ktakami/.edm/envs/chaco-dev/lib/python2.7/site-packages/chaco/scales/time_scale.py", line 137, in trange_years
    dt = datetime(dt_start.year-dyears, 1, 1, 0, 0, 0, 0)
ValueError: year is out of range
```

**OS, Python version:** 
OSX, Python 2.7

splits from #385

**Comment by siddhantwahal** [comment]
The following demos also break when the user zooms out too much
* `shell/dates.py`
* `financial/correlations.py`
* `financial/stock_prices.py`

**Comment by midhun-pm** [comment]
PR #500 Fixes the original issue. 
Following bugs remain.
> The following demos also break when the user zooms out too much
> 
>     * `shell/dates.py`
> 
>     * `financial/correlations.py`
> 
>     * `financial/stock_prices.py`
