### ISSUE TITLE
Wx tracebacks on Appveyor CI runs on Python 2

### ISSUE THREAD

**Issue by rahulporuri** [enthought/chaco#449]
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\users\appveyor\.edm\envs\chaco-test-2.7-wx\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
PyAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed
Error in sys.exitfunc:
Traceback (most recent call last):
  File "c:\users\appveyor\.edm\envs\chaco-test-2.7-wx\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
wx._core.PyAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed
```

_Originally posted by @rahulporuri in https://github.com/enthought/chaco/pull/445#issuecomment-498010336_

**Comment by rahulporuri** [comment]
See https://github.com/enthought/chaco/pull/445#issuecomment-500111007 for what could possible be causing the tracebacks.

**Comment by rahulporuri** [comment]
Closing as we dont care about Python 2 anymore.
