### ISSUE TITLE
BUG: TestLargestTriangleThreeBuckets Failures

### ISSUE THREAD

**Issue by skailasa** [enthought/chaco#454]
**Problem Description**
Failing test with assertion errors
**Reproduction Steps:**

[Steps to reproduce issue here.]

```python
# Code to reproduce issue here
python -m unittest
```

Traceback

```bash
======================================================================
FAIL: test_concave_down (chaco.downsample.tests.test_lttb.TestLargestTriangleThreeBuckets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sri/PycharmProjects/chaco/chaco/downsample/tests/test_lttb.py", line 105, in test_concave_down
    self.assertEqual(result.shape, (12, 2))
AssertionError: Tuples differ: (101, 2) != (12, 2)

First differing element 0:
101
12

- (101, 2)
?   ^^

+ (12, 2)
?   ^


======================================================================
FAIL: test_concave_up (chaco.downsample.tests.test_lttb.TestLargestTriangleThreeBuckets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sri/PycharmProjects/chaco/chaco/downsample/tests/test_lttb.py", line 91, in test_concave_up
    self.assertEqual(result.shape, (12, 2))
AssertionError: Tuples differ: (101, 2) != (12, 2)

First differing element 0:
101
12

- (101, 2)
?   ^^

+ (12, 2)
?   ^


======================================================================
FAIL: test_linear (chaco.downsample.tests.test_lttb.TestLargestTriangleThreeBuckets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sri/PycharmProjects/chaco/chaco/downsample/tests/test_lttb.py", line 46, in test_linear
    self.assertEqual(result.shape, (12, 2))
AssertionError: Tuples differ: (101, 2) != (12, 2)

First differing element 0:
101
12

- (101, 2)
?   ^^

+ (12, 2)
?   ^


======================================================================
FAIL: test_spike (chaco.downsample.tests.test_lttb.TestLargestTriangleThreeBuckets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sri/PycharmProjects/chaco/chaco/downsample/tests/test_lttb.py", line 71, in test_spike
    self.assertEqual(result.shape, (5, 2))
AssertionError: Tuples differ: (31, 2) != (5, 2)

First differing element 0:
31
5

- (31, 2)
?  ^^

+ (5, 2)
?  ^


======================================================================
FAIL: test_three_buckets (chaco.downsample.tests.test_lttb.TestLargestTriangleThreeBuckets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sri/PycharmProjects/chaco/chaco/downsample/tests/test_lttb.py", line 155, in test_three_buckets
    assert_array_equal(result, [[0.0, 0.0]]*3)
  File "/Users/sri/.edm/envs/chaco/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 865, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Users/sri/.edm/envs/chaco/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 740, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(shapes (10, 2), (3, 2) mismatch)
 x: array([[0., 0.],
       [0., 0.],
       [0., 0.],...
 y: array([[0., 0.],
       [0., 0.],
       [0., 0.]])

----------------------------------------------------------------------
```

**OS, Python version:** [Enter OS name and Python version]
MacOS 10.14.5, Py3.60, Numpy 1.15.4

**Comment by rahulporuri** [comment]
closing as we're not seeing this anymore.
