### ISSUE TITLE
advanced/scalar_image_function_inspector_old.py Fails to run

### ISSUE THREAD

**Issue by aaronayres35** [enthought/chaco#558]
When attempting to run the example https://github.com/enthought/chaco/blob/master/examples/demo/advanced/scalar_image_function_inspector_old.py
The following error occurs:
```
Traceback (most recent call last):
  File "/Users/aayres/.edm/envs/chaco-test-3.6-pyside2/lib/python3.6/site-packages/enable/qt4/base_window.py", line 213, in paintEvent
    self.handler.paintEvent(event)
  File "/Users/aayres/.edm/envs/chaco-test-3.6-pyside2/lib/python3.6/site-packages/enable/qt4/base_window.py", line 65, in paintEvent
    self._enable_window._paint(event)
  File "/Users/aayres/.edm/envs/chaco-test-3.6-pyside2/lib/python3.6/site-packages/enable/abstract_window.py", line 471, in _paint
    self.component.draw(gc, view_bounds=(0, 0, size[0], size[1]))
  File "/Users/aayres/.edm/envs/chaco-test-3.6-pyside2/lib/python3.6/site-packages/enable/component.py", line 427, in draw
    self._draw(gc, view_bounds, mode)
  File "/Users/aayres/.edm/envs/chaco-test-3.6-pyside2/lib/python3.6/site-packages/enable/component.py", line 779, in _draw
    self._dispatch_draw(layer, gc, view_bounds, mode)
  File "/Users/aayres/.edm/envs/chaco-test-3.6-pyside2/lib/python3.6/site-packages/enable/container.py", line 273, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/aayres/.edm/envs/chaco-test-3.6-pyside2/lib/python3.6/site-packages/enable/container.py", line 271, in _dispatch_draw
    component._draw(gc, new_bounds, mode)
  File "/Users/aayres/.edm/envs/chaco-test-3.6-pyside2/lib/python3.6/site-packages/enable/component.py", line 769, in _draw
    self._dispatch_draw(layer, bb, view_bounds, mode)
  File "/Users/aayres/.edm/envs/chaco-test-3.6-pyside2/lib/python3.6/site-packages/enable/container.py", line 273, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/aayres/.edm/envs/chaco-test-3.6-pyside2/lib/python3.6/site-packages/enable/component.py", line 799, in _dispatch_draw
    handler(gc, view_bounds, mode)
  File "/Users/aayres/.edm/envs/chaco-test-3.6-pyside2/lib/python3.6/site-packages/chaco/base_2d_plot.py", line 204, in _draw_image
    self._render(gc)
  File "/Users/aayres/.edm/envs/chaco-test-3.6-pyside2/lib/python3.6/site-packages/chaco/contour_poly_plot.py", line 46, in _render
    self._update_polys()
  File "/Users/aayres/.edm/envs/chaco-test-3.6-pyside2/lib/python3.6/site-packages/chaco/contour_poly_plot.py", line 86, in _update_polys
    c = Cntr(xg, yg, data, ~mask)
ValueError: Arguments x, y, z, mask (if present) must have the same dimensions.
```

**Reproduction Steps:**

```
$ python ci/edmtool.py install --toolkit=pyside2
$ edm shell -e chaco-test-3.6-pyside2
# navigate to directory 
$ python scalar_image_function_inspector_old.py
```

**Comment by rahulporuri** [comment]
FTR, it looks like the `_old.py` file was created in this commit - https://github.com/enthought/chaco/commit/f7b9393deeb8327b708baa98fad97ad781615044#diff-fbff4793962cec98215d7102d12c7cdbf8fc28c3d945785ea92af3b36118bfe8 - which states that the non old version was not working in the chaco demo application

**Comment by aaronayres35** [comment]
closing as this was removed in #689
