### ISSUE TITLE
Warnings when the testsuite is run on Python 3.8

### ISSUE THREAD

**Issue by rahulporuri** [enthought/chaco#664]
```
c:\users\rporuri\work\github\ets\chaco\chaco\color_mapper.py:337: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.color_depth is "rgba":
c:\users\rporuri\work\github\ets\chaco\chaco\tools\toolbars\plot_toolbar.py:228: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.location is "top":
c:\users\rporuri\work\github\ets\chaco\chaco\tools\toolbars\plot_toolbar.py:241: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif self.location is "bottom":
c:\users\rporuri\work\github\ets\chaco\chaco\tools\toolbars\plot_toolbar.py:248: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif self.location is "left":
c:\users\rporuri\work\github\ets\chaco\chaco\shell\plot_maker.py:417: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if type is "poly":
c:\users\rporuri\work\github\ets\chaco\chaco\axis.py:680: RuntimeWarning: invalid value encountered in true_divide
  self._axis_pixel_vector = self._axis_vector / sqrt(
c:\users\rporuri\work\github\ets\chaco\chaco\data_range_1d.py:276: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._high_setting != val:
c:\users\rporuri\work\github\ets\chaco\chaco\data_range_1d.py:283: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if val == "auto":
c:\users\rporuri\work\github\ets\chaco\chaco\data_range_1d.py:290: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif val == "track":
c:\users\rporuri\work\github\ets\chaco\chaco\tools\lasso_selection.py:152:
DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself.
Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self._active_selection = empty((0, 2), dtype=numpy.bool)
c:\users\rporuri\work\github\ets\chaco\chaco\tools\lasso_selection.py:156:
DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself.
Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  len(self.selection_datasource.get_data()), dtype=numpy.bool
c:\users\rporuri\work\github\ets\chaco\chaco\tools\lasso_selection.py:273:
DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself.
Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self.selection_datasource._data.shape, dtype=numpy.bool
c:\users\rporuri\work\github\ets\chaco\chaco\tools\lasso_selection.py:191:
DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself.
Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self._active_selection = empty((0, 2), dtype=numpy.bool)
```

Note also that two errors were observed - which got fixed by installing the `mock` library.

```
======================================================================
ERROR: chaco.tests.test_cmap_image_plot (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: chaco.tests.test_cmap_image_plot
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\Users\rporuri\work\github\cp38-venv-test-ets-pkgs\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "c:\users\rporuri\work\github\ets\chaco\chaco\tests\test_cmap_image_plot.py", line 3, in <module>
    import mock
  File "C:\Users\rporuri\work\github\cp38-venv-test-ets-pkgs\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'mock'

======================================================================
ERROR: chaco.tools.tests.test_range_zoom (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: chaco.tools.tests.test_range_zoom
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\Users\rporuri\work\github\cp38-venv-test-ets-pkgs\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "c:\users\rporuri\work\github\ets\chaco\chaco\tools\tests\test_range_zoom.py", line 3, in <module>
    import mock
  File "C:\Users\rporuri\work\github\cp38-venv-test-ets-pkgs\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'mock'
```

<details><summary>output of pip freeze</summary>

```
apptools==5.1.0
attrs==20.3.0
backcall==0.2.0
celiagg==2.1.1
-e git+git@github.com:enthought/chaco.git@1ed123cc65d4fd2b9a53a238cd584f8c5dfcac68#egg=chaco
colorama==0.4.4
configobj==5.0.6
Cython==0.29.22
decorator==5.0.7
enable @ file:///C:/Users/rporuri/Downloads/enable-5.1.0-cp38-cp38-win_amd64.whl
-e git+git@github.com:enthought/envisage.git@d62af08e75c5555e69c4fc4688393dee737680e8#egg=envisage
fonttools==4.22.0
hypothesis==6.9.2
importlib-metadata==3.10.1
importlib-resources==5.1.2
ipykernel==5.5.3
ipython==7.22.0
ipython-genutils==0.2.0
jedi==0.18.0
jupyter-client==6.1.12
jupyter-core==4.7.1
kiwisolver==1.3.1
mock==4.0.3
numexpr==2.7.3
numpy==1.20.2
packaging==20.9
pandas==1.2.4
parso==0.8.2
pickleshare==0.7.5
Pillow==8.2.0
prompt-toolkit==3.0.18
-e git+git@github.com:enthought/pyface.git@004d6ee43acaa51b17e78707f8aeb1118d818725#egg=pyface
pygarrayimage==1.0
pyglet==1.5.16
Pygments==2.8.1
pyparsing==2.4.7
PyPDF2==1.26.0
PyQt5-Qt5==5.15.2
PyQt5-sip==12.8.1
PySide2==5.15.2
python-dateutil==2.8.1
pytz==2021.1
pywin32==300
pyzmq==22.0.3
reportlab==3.5.67
shiboken2==5.15.2
six==1.15.0
sortedcontainers==2.3.0
tables==3.6.1
tornado==6.1
traitlets==5.0.5
-e git+git@github.com:enthought/traits.git@17c60780393d6c885d45f727209c65d8a1d458fc#egg=traits
-e git+git@github.com:enthought/traits-futures.git@9ec7f4567b06c1afd6f582301d69e87dfdbac3ee#egg=traits_futures
-e git+git@github.com:enthought/traitsui.git@8c21ab1fe9f526cf4ffcc1901739ca4661a7a450#egg=traitsui
wcwidth==0.2.5
zipp==3.4.1
```

</details>

**Comment by corranwebster** [comment]
These are resolved.
