### ISSUE TITLE
Chaco 6.0.0 installation failed with Numpy 1.26.4

### ISSUE THREAD

**Issue by henridbr** [enthought/chaco#910]
**Problem Description**
Failing to build wheel for chaco due to numpy version check.
With Python 3.12.2, numpy 1.26.4, chaco 6.0.0 installation failed.
Script chaco/plots/contour/cntr.c is calling for files which does not exist in numpy anymore.

**Reproduction Steps:**
```
pip install chaco 
[...]
creating build\temp.win-amd64-cpython-312\Release\chaco\plots\contour
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DNUMPY -IC:\Users\henri\AppData\Local\Temp\pip-build-env-yp634vpe\overlay\Lib\site-packages\numpy\core\include "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcchaco/plots/contour/cntr.c /Fobuild\temp.win-amd64-cpython-312\Release\chaco/plots/contour/cntr.obj
      cntr.c
      C:\Users\henri\AppData\Local\Temp\pip-build-env-yp634vpe\overlay\Lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
      chaco/plots/contour/cntr.c(35): fatal error C1083: Impossible d'ouvrir le fichier includeÿ: 'numpy/oldnumeric.h'ÿ: No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chaco
Failed to build chaco
ERROR: Could not build wheels for chaco, which is required to install pyproject.toml-based `projects`
```
**Expected behavior:**
To get chaco installed, chaco/plots/contour/cntr.c might be corrected. 

**OS, Python version:** [Win 11, Visual Studio Code and Python 3.12.2]

**Comment by limpkin** [comment]
I'm also experiencing this issue... did you manage to find a local fix?

**Comment by henridbr** [comment]
Hi limpkin,

I wanted to use the GUI of your CDM324 Doppler Speed Sensor, but was stopped by this issue. 
This is the lines inside cntr.c which seems are the source of the issue.
It seems it is the place to introduce the line
_Warning Msg: Using deprecated NumPy API, disable it with_ 
`
#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
`
 I tried to correct it but failed.
```

#ifdef NUMPY
#include "numpy/arrayobject.h"
# ifndef PyArray_SBYTE
#  include "numpy/oldnumeric.h"
#  include "numpy/old_defines.h"
# endif
#else
# include "Numeric/arrayobject.h"
# define PyArray_UBYTELTR 'b'
#endif

```
Seems chaco has not been maintained since last year.
Regards.
Henri

**Comment by limpkin** [comment]
Yup, another customer reported that issue to me so I'm trying to see what I can do...
I'm going to experiment and report back

**Comment by limpkin** [comment]
so I innocently copy pasted the contents of https://github.com/huggingface/neuralcoref/blob/master/include/numpy/oldnumeric.h into the #ifdef but am now getting a whole new bunch of issues...

` Error compiling Cython file:
      ------------------------------------------------------------
      ...
      # Thanks for using Enthought open source!
      import cython
      import numpy as np
      from numpy cimport uint8_t

      cimport _marker_renderer
              ^
      ------------------------------------------------------------

      kiva\_marker_renderer.pyx:14:8: '_marker_renderer.pxd' not found

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      import numpy as np
      from numpy cimport uint8_t

      cimport _marker_renderer

      ctypedef _marker_renderer.marker_renderer_base renderer_base_t
               ^
      ------------------------------------------------------------

      kiva\_marker_renderer.pyx:16:9: 'marker_renderer_base' is not a type identifier

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

              self._this.transform(_sx, _sy, _shx, _shy, _tx, _ty)


      # Template specializations
      ctypedef _marker_renderer.marker_renderer[_marker_renderer.pixfmt_abgr32] renderer_abgr32_t
               ^
      ------------------------------------------------------------

      kiva\_marker_renderer.pyx:91:9: 'marker_renderer' is not a type identifier

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self._this.transform(_sx, _sy, _shx, _shy, _tx, _ty)


      # Template specializations
      ctypedef _marker_renderer.marker_renderer[_marker_renderer.pixfmt_abgr32] renderer_abgr32_t
      ctypedef _marker_renderer.marker_renderer[_marker_renderer.pixfmt_argb32] renderer_argb32_t
               ^`

**Comment by limpkin** [comment]
ok so I managed to install everything but that wasn't straight forward. In short, I found a previous version of the missing oldnumeric.h file, and pasted its contents into the cntr.ch
You'll need to:
- dowload & unzip my repo clone: https://github.com/limpkin/chaco
- go into the folder with cmd, then 'pip install -e .'
- download & unzip enable: https://github.com/enthought/enable
- go into the folder with cmd, then 'pip install -e .'

**Comment by henridbr** [comment]
Thank you for this trick, it works fine for me.
Sorry for my mistake when answering, I quoted a wrong script.

**Comment by capn-freako** [comment]
https://github.com/enthought/chaco/pull/913

**Comment by limpkin** [comment]
that looks easier...

**Comment by fred4ets** [comment]
Try to compile enable from your repo, limpkin, with Python 3.13/NumPy 2.2.3/Cython 3.0.11 on Debian x86_64, I get the following error messages:

Obtaining file:///home/fredo/enable-main
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from enable==6.1.0.dev0) (2.2.3)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from enable==6.1.0.dev0) (11.1.0)
Requirement already satisfied: traits>=6.2.0 in /usr/lib/python3/dist-packages (from enable==6.1.0.dev0) (6.4.3)
Requirement already satisfied: traitsui in /usr/lib/python3/dist-packages (from enable==6.1.0.dev0) (8.0.0)
Requirement already satisfied: pyface>=7.2.0 in /usr/lib/python3/dist-packages (from enable==6.1.0.dev0) (8.0.0)
Requirement already satisfied: fonttools in /usr/lib/python3/dist-packages (from enable==6.1.0.dev0) (4.55.3)
Building wheels for collected packages: enable
  Building editable for enable (pyproject.toml): started
  Building editable for enable (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building editable for enable (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [231 lines of output]
      /tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!
      
              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:
      
              License :: OSI Approved :: BSD License
      
              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************
      
      !!
        self._finalize_license_expression()
      running editable_wheel
      creating /tmp/pip-wheel-bqgdhgpv/.tmp-7_bq067c/enable.egg-info
      writing /tmp/pip-wheel-bqgdhgpv/.tmp-7_bq067c/enable.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-wheel-bqgdhgpv/.tmp-7_bq067c/enable.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-wheel-bqgdhgpv/.tmp-7_bq067c/enable.egg-info/entry_points.txt
      writing requirements to /tmp/pip-wheel-bqgdhgpv/.tmp-7_bq067c/enable.egg-info/requires.txt
      writing top-level names to /tmp/pip-wheel-bqgdhgpv/.tmp-7_bq067c/enable.egg-info/top_level.txt
      writing manifest file '/tmp/pip-wheel-bqgdhgpv/.tmp-7_bq067c/enable.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-wheel-bqgdhgpv/.tmp-7_bq067c/enable.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'docs/kiva/agg/notes'
      warning: no files found matching '*.h' under directory 'kiva/gl'
      warning: no files found matching '*.cpp' under directory 'kiva/gl'
      warning: no files found matching '*.i' under directory 'kiva/gl'
      warning: no files found matching 'LICENSE_*' under directory 'kiva/gl'
      warning: no files found matching '*.pxd' under directory 'kiva/quartz'
      adding license file 'LICENSE.txt'
      writing manifest file '/tmp/pip-wheel-bqgdhgpv/.tmp-7_bq067c/enable.egg-info/SOURCES.txt'
      creating '/tmp/pip-wheel-bqgdhgpv/.tmp-7_bq067c/enable-6.1.0.dev0.dist-info'
      creating /tmp/pip-wheel-bqgdhgpv/.tmp-7_bq067c/enable-6.1.0.dev0.dist-info/WHEEL
      running build_py
      running build_ext
      cythoning kiva/_cython_speedups.pyx to kiva/_cython_speedups.cpp
      /tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/fredo/enable-main/kiva/_cython_speedups.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      cythoning kiva/_marker_renderer.pyx to kiva/_marker_renderer.cpp
      /tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/fredo/enable-main/kiva/_marker_renderer.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      building 'kiva._cython_speedups' extension
      creating /tmp/tmpaitcnuvt.build-temp/kiva
      x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -Ikiva -I/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/numpy/_core/include -I/usr/include/python3.13 -c kiva/_cython_speedups.cpp -o /tmp/tmpaitcnuvt.build-temp/kiva/_cython_speedups.o
      In file included from /tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/numpy/_core/include/numpy/ndarraytypes.h:1913,
                       from /tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/numpy/_core/include/numpy/ndarrayobject.h:12,
                       from /tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/numpy/_core/include/numpy/arrayobject.h:5,
                       from kiva/_cython_speedups.cpp:769:
      /tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/numpy/_core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
      kiva/_cython_speedups.cpp:856:72: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]
        856 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u) {
            |                                                                        ^
      In file included from /usr/include/python3.13/unicodeobject.h:1014,
                       from /usr/include/python3.13/Python.h:79,
                       from kiva/_cython_speedups.cpp:6:
      /usr/include/python3.13/cpython/unicodeobject.h:10:37: note: declared here
         10 | Py_DEPRECATED(3.13) typedef wchar_t Py_UNICODE;
            |                                     ^~~~~~~~~~
      kiva/_cython_speedups.cpp: In function ‘size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE*)’:
      kiva/_cython_speedups.cpp:857:23: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]
        857 |     const Py_UNICODE *u_end = u;
            |                       ^~~~~
      /usr/include/python3.13/cpython/unicodeobject.h:10:37: note: declared here
         10 | Py_DEPRECATED(3.13) typedef wchar_t Py_UNICODE;
            |                                     ^~~~~~~~~~
      kiva/_cython_speedups.cpp: In function ‘int __Pyx_PyList_Extend(PyObject*, PyObject*)’:
      kiva/_cython_speedups.cpp:1908:22: error: ‘_PyList_Extend’ was not declared in this scope; did you mean ‘PyList_Extend’?
       1908 |     PyObject* none = _PyList_Extend((PyListObject*)L, v);
            |                      ^~~~~~~~~~~~~~
            |                      PyList_Extend
      kiva/_cython_speedups.cpp: In function ‘void __Pyx_init_assertions_enabled()’:
      kiva/_cython_speedups.cpp:1946:39: error: ‘_PyInterpreterState_GetConfig’ was not declared in this scope; did you mean ‘PyInterpreterState_GetID’?
       1946 |     __pyx_assertions_enabled_flag = ! _PyInterpreterState_GetConfig(__Pyx_PyThreadState_Current->interp)->optimization_level;
            |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            |                                       PyInterpreterState_GetID
      kiva/_cython_speedups.cpp: In function ‘npy_uint8 __Pyx_PyInt_As_npy_uint8(PyObject*)’:
      kiva/_cython_speedups.cpp:23917:46: error: too few arguments to function ‘int _PyLong_AsByteArray(PyLongObject*, unsigned char*, size_t, int, int, int)’
      23917 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
      23918 |                                               bytes, sizeof(val),
            |                                               ~~~~~~~~~~~~~~~~~~~
      23919 |                                               is_little, !is_unsigned);
            |                                               ~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /usr/include/python3.13/longobject.h:107,
                       from /usr/include/python3.13/Python.h:81:
      /usr/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      kiva/_cython_speedups.cpp: In function ‘int __Pyx_PyInt_As_int(PyObject*)’:
      kiva/_cython_speedups.cpp:24113:46: error: too few arguments to function ‘int _PyLong_AsByteArray(PyLongObject*, unsigned char*, size_t, int, int, int)’
      24113 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
      24114 |                                               bytes, sizeof(val),
            |                                               ~~~~~~~~~~~~~~~~~~~
      24115 |                                               is_little, !is_unsigned);
            |                                               ~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      kiva/_cython_speedups.cpp: In function ‘long int __Pyx_PyInt_As_long(PyObject*)’:
      kiva/_cython_speedups.cpp:24309:46: error: too few arguments to function ‘int _PyLong_AsByteArray(PyLongObject*, unsigned char*, size_t, int, int, int)’
      24309 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
      24310 |                                               bytes, sizeof(val),
            |                                               ~~~~~~~~~~~~~~~~~~~
      24311 |                                               is_little, !is_unsigned);
            |                                               ~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      kiva/_cython_speedups.cpp: In function ‘char __Pyx_PyInt_As_char(PyObject*)’:
      kiva/_cython_speedups.cpp:24543:46: error: too few arguments to function ‘int _PyLong_AsByteArray(PyLongObject*, unsigned char*, size_t, int, int, int)’
      24543 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
            |                           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
      24544 |                                               bytes, sizeof(val),
            |                                               ~~~~~~~~~~~~~~~~~~~
      24545 |                                               is_little, !is_unsigned);
            |                                               ~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/python3.13/cpython/longobject.h:111:17: note: declared here
        111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
            |                 ^~~~~~~~~~~~~~~~~~~
      Traceback (most recent call last):
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/spawn.py", line 87, in spawn
          subprocess.check_call(cmd, env=_inject_macos_ver(env))
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.13/subprocess.py", line 419, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/bin/x86_64-linux-gnu-g++', '-fno-strict-overflow', '-Wsign-compare', '-DNDEBUG', '-g', '-O2', '-Wall', '-fPIC', '-Ikiva', '-I/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/numpy/_core/include', '-I/usr/include/python3.13', '-c', 'kiva/_cython_speedups.cpp', '-o', '/tmp/tmpaitcnuvt.build-temp/kiva/_cython_speedups.o']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/compilers/C/unix.py", line 217, in _compile
          self.spawn(
          ~~~~~~~~~~^
              compiler_so_cxx + cc_args + [src, '-o', obj] + extra_postargs
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/compilers/C/base.py", line 1158, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
          ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/spawn.py", line 93, in spawn
          raise DistutilsExecError(
              f"command {_debug(cmd)!r} failed with exit code {err.returncode}"
          ) from err
      distutils.errors.DistutilsExecError: command '/bin/x86_64-linux-gnu-g++' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/command/editable_wheel.py", line 139, in run
          self._create_wheel_file(bdist_wheel)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/command/editable_wheel.py", line 340, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
                           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/command/editable_wheel.py", line 263, in _run_build_commands
          self._run_build_subcommands()
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/command/editable_wheel.py", line 290, in _run_build_subcommands
          self.run_command(name)
          ~~~~~~~~~~~~~~~~^^^^^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/cmd.py", line 357, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/dist.py", line 1104, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/dist.py", line 1021, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
          ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/command/build_ext.py", line 368, in run
          self.build_extensions()
          ~~~~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
          _build_ext.build_ext.build_extensions(self)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/command/build_ext.py", line 484, in build_extensions
          self._build_extensions_serial()
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/command/build_ext.py", line 510, in _build_extensions_serial
          self.build_extension(ext)
          ~~~~~~~~~~~~~~~~~~~~^^^^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/command/build_ext.py", line 565, in build_extension
          objects = self.compiler.compile(
              sources,
          ...<5 lines>...
              depends=ext.depends,
          )
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/compilers/C/base.py", line 655, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
          ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/compilers/C/unix.py", line 223, in _compile
          raise CompileError(msg)
      distutils.compilers.C.errors.CompileError: command '/bin/x86_64-linux-gnu-g++' failed with exit code 1
      /tmp/pip-build-env-rido0jrn/overlay/local/lib/python3.13/dist-packages/setuptools/_distutils/dist.py:1021: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `enable` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
      
      !!
        cmd_obj.run()
      error: command '/bin/x86_64-linux-gnu-g++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for enable
Failed to build enable
ERROR: Failed to build installable wheels for some pyproject.toml based projects (enable)
